<a href="https://colab.research.google.com/github/InannaxX07/ANUSHREE_SCIFOR/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define a mock YOLO-like model function that generates random detections
def yolo_like_model(input_image):
    # Simulate bounding box predictions and confidence scores
    num_boxes = np.random.randint(1, 5)  # Randomly choose number of boxes
    boxes = []
    scores = []
    classes = []

    for _ in range(num_boxes):
        # Generate random box coordinates (center x, center y, width, height)
        box = np.random.rand(4)  # Replace with your actual detection logic
        boxes.append(box)

        # Generate random confidence score
        score = np.random.rand()  # Replace with confidence score from model
        scores.append(score)

        # Generate random class (for illustration purposes)
        cls = np.random.randint(0, 10)  # Replace with predicted class from model
        classes.append(cls)

    # Return mock detections
    return {'boxes': np.array(boxes), 'scores': np.array(scores), 'classes': np.array(classes)}

# Function to perform non-max suppression
def non_max_suppression(boxes, scores, threshold=0.5):
    # Simulate NMS (this is a placeholder and not a real implementation)
    return boxes, scores

# Function to preprocess input image (this is just a mock)
def preprocess_image(image_path):
    # Simulate loading and preprocessing an image (replace with actual logic)
    return np.random.rand(416, 416, 3)  # Replace with actual image processing logic

# Function to run inference on input image
def run_inference(image_path):
    # Simulate loading and preprocessing an image (replace with actual image loading logic)
    input_image = preprocess_image(image_path)

    # Perform inference using the mock YOLO-like model
    detections = yolo_like_model(input_image)

    # Perform non-max suppression on detections (this is a placeholder)
    filtered_boxes, filtered_scores = non_max_suppression(detections['boxes'], detections['scores'], threshold=0.5)

    # Print or process the filtered_boxes and filtered_scores
    print("Filtered Boxes:", filtered_boxes)
    print("Filtered Scores:", filtered_scores)

# Example usage
image_path = 'path_to_your_input_image.jpg'  # Replace with the path to your image
run_inference(image_path)

Filtered Boxes: [[0.9970498  0.05875196 0.77736253 0.23748787]
 [0.84942008 0.31126221 0.58331221 0.89548635]
 [0.55742184 0.85506454 0.41873602 0.46132901]
 [0.97767293 0.48581224 0.86415109 0.40397146]]
Filtered Scores: [0.04626404 0.47040315 0.37755803 0.87286468]
